### ISSUE TITLE
Can I import a local xml style file with r2cytoscape?

### ISSUE THREAD

**Issue by kozo2** [cytoscape/r2cytoscape#7]
I'm trying to import a local Style XML file with r2cytoscape.

As far as I saw https://github.com/cytoscape/r2cytoscape/tree/master/R ,
I thought that the function was not implemented yet.
Is this right? If it is so, Is there anything I can support you?

**Comment by AlexanderPico** [comment]
Good question! I don't see any support for this function in CyREST or commands... so we can't add it to the R library yet. I've sent an email to the David, the CyREST developer.

In the meantime, I'll transfer this feature request to the new RCy3 repo... https://github.com/cytoscape/RCy3/issues/1
