### ISSUE TITLE
Zenodo DOI request

### ISSUE THREAD

**Issue by kozo2** [cytoscape/r2cytoscape#8]
I'm using r2cytoscape in my own research.
I would like to cite r2cytoscape, so I would like you to attach a Zenodo DOI to this project.

To attach Zenodo DOI, please see
https://guides.github.com/activities/citable-code/

Thanks

**Comment by AlexanderPico** [comment]
Thanks Kozo,

But we are likely going to merge this project with RCy3 and discontinue it as it’s own repo. Details are still being worked out, but if this occurs then it would not be a good idea to cite (or even link to) the repo in your research. 

Citing Cytoscape would be sufficient and appropriate for now. 

Thanks!
 - Alex

**Comment by AlexanderPico** [comment]
Here's the new project repo: https://github.com/cytoscape/RCy3.  It's not ready for general use yet. We will be completing a major refactor and then submitting to bioconductor as RCy3 version 2.0. This new effort is the one I encourage using and citing in projects going forward.

**Comment by kozo2** [comment]
Thanks for the info.
I understood the situation.
For now I only cite Cytoscape.
